version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "3G"
      SPIGET_RESOURCES: "9089"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - ./minecraft-data:/data
  backups:
    image: itzg/mc-backup
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "15m"
      INITIAL_DELAY: "120"
    volumes:
    # mount the same volume used by server, but read-only
    - ./minecraft-data:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - ./mc-backups:/backups
    network_mode: "service:mc"
