version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565/tcp
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "3G"
      # WORLD: "https://minecraft-backups.us-southeast-1.linodeobjects.com/world-20220404-020652.tgz"
      WHITELIST_FILE: "https://raw.githubusercontent.com/ChrisDemahy/CODE_MC/main/whitelist.json"
      OPS_FILE: "https://raw.githubusercontent.com/ChrisDemahy/CODE_MC/main/ops.json"
      OVERRIDE_WHITELIST: "TRUE"
      OVERRIDE_OPS: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - ./minecraft-data:/data
    - ./worlds:/worlds:ro
    - ./extra:/extra:ro
    - ./plugins:/data/plugins:ro
  backups:
    image: itzg/mc-backup
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "15m"
      INITIAL_DELAY: "180"
      PAUSE_IF_NO_PLAYERS: "TRUE"
    volumes:
    # mount the same volume used by server, but read-only
    - ./minecraft-data:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - ./mc-backups:/backups
    network_mode: "service:mc"
