version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565/tcp
      - 19132:19132/udp
      # - 7091:7091/tcp
      # - 443:443/tcp
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "3G"
      # WORLD: "https://minecraft-backups.us-southeast-1.linodeobjects.com/world-20220404-020652.tgz"
      WHITELIST_FILE: "https://raw.githubusercontent.com/ChrisDemahy/CODE_MC/main/whitelist.json"
      OPS_FILE: "https://raw.githubusercontent.com/ChrisDemahy/CODE_MC/main/ops.json"
      OVERRIDE_WHITELIST: "TRUE"
      OVERRIDE_OPS: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      RESOURCE_PACK: "https://faithful.team/api/versions/1.18.zip"      
      DATAPACKS_FILE: "/data/datapacks.txt"
      # Datadog
      # ENABLE_JMX: "TRUE"
      # JMX_HOST: "localhost"
      # JVM_OPTS: "-javaagent:/extra/dd-java-agent.jar -Ddd.profiling.enabled=true -Ddd.appsec.enabled=true -Ddd.service=mc -Ddd.env=prod -XX:FlightRecorderOptions=stackdepth=256 -Ddd.logs.injection=true -Ddd.appsec.enabled=true -Ddd.trace.sample.rate=1 -Ddd.service=mc -Ddd.env=prod -Ddd.version=1.0"
      # DD_AGENT_HOST: "datadog-agent"
      # DD_TRACE_AGENT_PORT: 8126
      # DD_TRACE_AGENT_URL: http://datadog-agent:8126
      LOG_TIMESTAMP: "TRUE"
    labels:
      com.datadoghq.ad.logs: '["mc"]'

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - /mnt/minecraft/data:/data
    - ./worlds:/worlds:ro
    - ./extra:/extra:ro
    - ./plugins:/plugins:ro
    - /etc/timezone:/etc/timezone:ro
    - /var/run/datadog/:/var/run/datadog/
  monitor-java:
    image: itzg/mc-monitor
    command: export-for-prometheus

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - /etc/timezone:/etc/timezone:ro
    
    environment:
      EXPORT_SERVERS: mc
      DEBUG: "true"
    ports:
      - 10055:8080
    depends_on:
      - mc
  monitor-bedrock:
    image: itzg/mc-monitor
    command: export-for-prometheus

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - /etc/timezone:/etc/timezone:ro
    
    environment:
      EXPORT_BEDROCK_SERVERS: mc
      DEBUG: "true"
    ports:
      - 10056:8080
    depends_on:
      - mc
  backups:
    image: itzg/mc-backup
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "10m"
      INITIAL_DELAY: "180"
      PAUSE_IF_NO_PLAYERS: "TRUE"
      PRUNE_BACKUPS_DAYS: "1"
    volumes:
    # mount the same volume used by server, but read-only
    - /mnt/minecraft/data:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - ./mc-backups:/backups
    - /etc/timezone:/etc/timezone:ro
    network_mode: "service:mc"
  
  nginx:
    #image: nginx
    build: ./web
    
    command: [nginx-debug, '-g', 'daemon off;']
    
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      DD_AGENT_HOST: "datadog-agent"
      DD_TRACE_AGENT_PORT: 8126
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certs:/etc/ssl:ro
    - /etc/timezone:/etc/timezone:ro
    - /var/run/datadog/:/var/run/datadog/
    - ./dd-config.json:/etc/nginx/dd-config.json:ro
    ports:
     - 443:443/tcp
networks:
  default:
    external:
      name: datadog-network
